
# simple way of creating a qrcode. Approach - 1

import qrcode   # importing qrcode module
import image   # even we are not using the image module, qrcode will use this module internally so, we have to import these modules also
# my_qr = my_qr.make("This is coming from qr sfedsf.")    # adding data to the qrcode
# my_qr.save("myimage.png")   # saving the qrcode to the myimage.png file

# simple way of creating a qrcode. Approach - 2

data = "one qr for all payments."
 
qr = qrcode.QRCode(version = 1,  # integer value from 1-40, responsible for controlling the size of qr, where 1 is small and 40 is large.
                   box_size = 10, # this also describes the size of the qr by controlling how many pixels each “box” of the QR code
                   border = 1)  # this gives border to the qr, which starts from the integer value 1
 
# qr --- is a object generated by the qrcode 
qr.add_data("www.google.com")  # you can add text, linl, youtube video or anything...
 
qr.make(fit = True)  # used to ensures that the entire dimension of the QR Code is utilized, even the given data could fit into less number of boxes.
img = qr.make_image(fill_color = 'red',   # converting the qr object to image and adding the colours to the qr code.
                    back_color = 'white') # back_color >> background color
img.save('myimage.png') 

# use paytm scanner for better result as it will redirect to the page when you give any link. Some scanners won't redirect to the 
# link, simply they will show the link.
